/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SellerSettingsRouteImport } from './routes/seller/settings'
import { Route as SellerReviewsRouteImport } from './routes/seller/reviews'
import { Route as SellerProductsRouteImport } from './routes/seller/products'
import { Route as SellerPendingRouteImport } from './routes/seller/pending'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerEarningsRouteImport } from './routes/seller/earnings'
import { Route as SellerAddProductRouteImport } from './routes/seller/add-product'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CustomerReviewsRouteImport } from './routes/customer/reviews'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerPaymentsRouteImport } from './routes/customer/payments'
import { Route as CustomerAddressesRouteImport } from './routes/customer/addresses'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSellersRouteImport } from './routes/admin/sellers'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPendingRoute = SellerPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerEarningsRoute = SellerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAddProductRoute = SellerAddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => SellerRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const CustomerReviewsRoute = CustomerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/add-product': typeof SellerAddProductRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pending': typeof SellerPendingRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/add-product': typeof SellerAddProductRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pending': typeof SellerPendingRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/add-product': typeof SellerAddProductRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/pending': typeof SellerPendingRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/login'
    | '/orders'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/orders/$id'
    | '/products/$id'
    | '/seller/add-product'
    | '/seller/earnings'
    | '/seller/orders'
    | '/seller/pending'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/login'
    | '/orders'
    | '/shop'
    | '/wishlist'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/orders/$id'
    | '/products/$id'
    | '/seller/add-product'
    | '/seller/earnings'
    | '/seller/orders'
    | '/seller/pending'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/login'
    | '/orders'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/orders/$id'
    | '/products/$id'
    | '/seller/add-product'
    | '/seller/earnings'
    | '/seller/orders'
    | '/seller/pending'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/admin/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  SellerRoute: typeof SellerRouteWithChildren
  ShopRoute: typeof ShopRoute
  WishlistRoute: typeof WishlistRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/pending': {
      id: '/seller/pending'
      path: '/pending'
      fullPath: '/seller/pending'
      preLoaderRoute: typeof SellerPendingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/earnings': {
      id: '/seller/earnings'
      path: '/earnings'
      fullPath: '/seller/earnings'
      preLoaderRoute: typeof SellerEarningsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/add-product': {
      id: '/seller/add-product'
      path: '/add-product'
      fullPath: '/seller/add-product'
      preLoaderRoute: typeof SellerAddProductRouteImport
      parentRoute: typeof SellerRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/customer/reviews': {
      id: '/customer/reviews'
      path: '/reviews'
      fullPath: '/customer/reviews'
      preLoaderRoute: typeof CustomerReviewsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments': {
      id: '/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerReviewsRoute: typeof CustomerReviewsRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerPaymentsRoute: CustomerPaymentsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerReviewsRoute: CustomerReviewsRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface SellerRouteChildren {
  SellerAddProductRoute: typeof SellerAddProductRoute
  SellerEarningsRoute: typeof SellerEarningsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPendingRoute: typeof SellerPendingRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAddProductRoute: SellerAddProductRoute,
  SellerEarningsRoute: SellerEarningsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPendingRoute: SellerPendingRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  SellerRoute: SellerRouteWithChildren,
  ShopRoute: ShopRoute,
  WishlistRoute: WishlistRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
